### ISSUE TITLE
PersistentTuple should be the default

### ISSUE THREAD

**Issue by kseo** [localvoid/tuple#6]
Currently, Tuple classes are mutable and PersistentTuple classes are immutable. But this seems a bit unconventional to me because tuples are usually immutable data structures in most programming languages.

I think it is better to keep only the immutable version and rename it to Tuple. Or we can at least make the immutable version default and rename the mutable version to MutableTuple. I prefer the former because keeping two versions of tuple make things unnecessarily complicated. e..g, defining equality between two versions.

**Comment by localvoid** [comment]
Yes, I think it is a good idea.

Would you like to take maintainership over this package? I'll transfer to you the ownership rights on pub.dartlang.org ,so you can upload new versions.

**Comment by kseo** [comment]
Okay. I will take over this package and make the changes I suggested. Thanks.

**Comment by localvoid** [comment]
I've added "kwangyul.seo@gmail.com" email to the uploaders list.

**Comment by kseo** [comment]
Done! https://github.com/kseo/tuple/commit/e7d33abc6fd9c6e273258b124a03b65a53337f97

I bumped the version to 0.2.0 and uploaded it to the pub.
